-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_itemmanager_settings`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_itemmanager_settings
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_itemmanager_settings` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique ItemmanagerSettings ID',
     `price_field_id` int unsigned NOT NULL   COMMENT 'FK to civicrm_price_field',
     `period_start_on` datetime   DEFAULT NULL COMMENT 'If non-zero, do not show this field before the date specified',
     `periods` int unsigned   DEFAULT NULL COMMENT 'Number of periods at start',
     `period_type` int unsigned   DEFAULT NULL COMMENT 'Period interval type',
     `itemmanager_successor_id` int unsigned   DEFAULT 0 COMMENT 'ID to itemmanager entry which is the successor' 
,
        PRIMARY KEY (`id`)
 
 
,          CONSTRAINT FK_civicrm_itemmanager_settings_price_field_id FOREIGN KEY (`price_field_id`) REFERENCES `civicrm_price_field`(`id`)   
)    ;

 